# Generated by Django 5.0.2 on 2024-03-18 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0001_initial"),
        ("wagtailcore", "0091_remove_revision_submitted_for_moderation"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSectionPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Раздел событий",
                "verbose_name_plural": "Разделы событий",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AlterModelOptions(
            name="eventpage",
            options={
                "verbose_name": "Страница события",
                "verbose_name_plural": "Страницы событий",
            },
        ),
        migrations.RemoveField(
            model_name="eventpage",
            name="body",
        ),
        migrations.RemoveField(
            model_name="eventpage",
            name="image",
        ),
    ]
