# Generated by Django 5.0.2 on 2024-03-21 09:20

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0007_eventpage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpage",
            name="end",
            field=models.DateTimeField(
                help_text="Выберите дату и время окончания события (необязательно)",
                null=True,
                verbose_name="Окончание события",
            ),
        ),
        migrations.AddField(
            model_name="eventpage",
            name="start",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 21, 12, 20, 13, 91350),
                help_text="Выберите дату и время начала события",
                verbose_name="Начало события",
            ),
        ),
    ]
