# Generated by Django 5.0.2 on 2024-03-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0008_eventpage_end_eventpage_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpage",
            name="start",
            field=models.DateTimeField(
                help_text="Выберите дату и время начала события",
                verbose_name="Начало события",
            ),
        ),
    ]
