# Generated by Django 5.0.2 on 2024-03-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0010_alter_eventpage_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsectionpage",
            name="elements_per_page",
            field=models.IntegerField(
                default=12,
                help_text="Сколько элементов будет отображаться на странице",
                verbose_name="Количество элементов на странице",
            ),
        ),
    ]
