# Generated by Django 5.0.2 on 2024-03-22 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0012_eventpage_gallery"),
        ("wagtailcore", "0091_remove_revision_submitted_for_moderation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpage",
            name="gallery",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите связанную страницу галереи",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Страница галереи",
            ),
        ),
    ]
