default_stages: [ commit, push ]
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.2
    hooks:
      - id: autopep8
  - repo: https://github.com/pycqa/flake8
    rev: '6.1.0'
    hooks:
      - id: flake8
        exclude: migrations
        additional_dependencies: [
           "flake8-2020",
           "flake8-absolute-import",
           "flake8-annotations-complexity",
           "flake8-annotations-coverage",
           "flake8-blind-except",
           "flake8-broken-line",
           "flake8-bugbear",
           "flake8-builtins",
           "flake8-class-attributes-order",
           "flake8-commas",
           "flake8-comprehensions",
           "flake8-debugger",
           "flake8-docstrings",
           "flake8-eradicate",
           "flake8-expression-complexity",
           "flake8-fixme",
           "flake8-functions",
           "flake8-functions-names",
           "flake8-if-statements",
           "flake8-multiline-containers",
           "flake8-obey-import-goat",
           "flake8-print",
           "flake8-printf-formatting",
           "flake8-quotes",
           "flake8-simplify",
           "flake8-string-format",
           "flake8-tidy-imports",
           "flake8-typing-imports",
           "flake8-variables-names",
        ]
  - repo: local
    hooks:
        - id: mypy
          name: mypy
          language: system
          entry: mypy --install-types --non-interactive
          args: ["--config=setup.cfg"]
          types: [ python ]
          require_serial: true
