# Generated by Django 5.0.2 on 2024-03-03 15:12

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_create_homepage"),
        ("wagtailcore", "0091_remove_revision_submitted_for_moderation"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("text", wagtail.blocks.RichTextBlock())], blank=True
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="featured_section_1",
            field=models.ForeignKey(
                blank=True,
                help_text="First featured section for the homepage. Will display up to three child items.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Featured section 1",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="featured_section_1_title",
            field=models.CharField(
                blank=True,
                help_text="Title to display above the promo copy",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_text",
            field=models.CharField(
                help_text="Write an introduction for the bakery",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Homepage image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="promo_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Promo image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="promo_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Write some promotional copy",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="promo_title",
            field=models.CharField(
                blank=True,
                help_text="Title to display above the promo copy",
                max_length=255,
            ),
        ),
    ]
