# Generated by Django 5.0.2 on 2024-03-19 07:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_remove_homepage_featured_section_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="body",
        ),
    ]
