# Generated by Django 5.0.2 on 2024-03-19 09:14

import django.db.models.deletion
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("help", "0003_remove_helpsectionpage_menu_order_index"),
        ("wagtailcore", "0091_remove_revision_submitted_for_moderation"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhonesPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "description",
                                wagtail.blocks.RichTextBlock(
                                    features=[
                                        "h2",
                                        "h3",
                                        "h4",
                                        "h5",
                                        "h6",
                                        "bold",
                                        "italic",
                                        "link",
                                        "code",
                                        "blockquote",
                                        "document-link",
                                    ],
                                    label="Текст",
                                ),
                            ),
                            (
                                "image_block",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Изображение", required=True
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.blocks.CharBlock(
                                                label="Подпись", required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "phones",
                    wagtail.fields.StreamField(
                        [
                            (
                                "header",
                                wagtail.blocks.RichTextBlock(
                                    features=["h2", "h3", "h4", "h5", "h6"],
                                    label="заголовок",
                                ),
                            ),
                            (
                                "phone_block",
                                wagtail.blocks.StreamBlock(
                                    [
                                        (
                                            "mobile_phone",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "phone",
                                                        wagtail.blocks.RegexBlock(
                                                            error_messages={
                                                                "invalid": "Не верно введен номер"
                                                            },
                                                            form_classname="Мобильный номер телефона",
                                                            help_text="Ввод без +7 в формате 9008887766",
                                                            max_length=10,
                                                            min_length=10,
                                                            regex="^[0-9]{10}$",
                                                            required=True,
                                                        ),
                                                    ),
                                                    (
                                                        "workplace",
                                                        wagtail.blocks.CharBlock(
                                                            label="Рабочее место",
                                                            required=True,
                                                        ),
                                                    ),
                                                    (
                                                        "employee",
                                                        wagtail.blocks.CharBlock(
                                                            label="Работник",
                                                            required=False,
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                        (
                                            "city_phone",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "phone",
                                                        wagtail.blocks.RegexBlock(
                                                            error_messages={
                                                                "invalid": "Не верно введен номер"
                                                            },
                                                            form_classname="Городской номер телефона",
                                                            help_text="Ввод без +74812 в формате 887766",
                                                            max_length=6,
                                                            min_length=6,
                                                            regex="^[0-9]{6}$",
                                                            required=True,
                                                        ),
                                                    ),
                                                    (
                                                        "workplace",
                                                        wagtail.blocks.CharBlock(
                                                            label="Рабочее место",
                                                            required=True,
                                                        ),
                                                    ),
                                                    (
                                                        "employee",
                                                        wagtail.blocks.CharBlock(
                                                            label="Работник",
                                                            required=False,
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                        (
                                            "internal_phone",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "phone",
                                                        wagtail.blocks.RegexBlock(
                                                            error_messages={
                                                                "invalid": "Не верно введен номер"
                                                            },
                                                            form_classname="Внутренний номер телефона",
                                                            help_text="Ввод в формате 123",
                                                            max_length=3,
                                                            min_length=3,
                                                            regex="^[0-9]{3}$",
                                                            required=True,
                                                        ),
                                                    ),
                                                    (
                                                        "workplace",
                                                        wagtail.blocks.CharBlock(
                                                            label="Рабочее место",
                                                            required=True,
                                                        ),
                                                    ),
                                                    (
                                                        "employee",
                                                        wagtail.blocks.CharBlock(
                                                            label="Работник",
                                                            required=False,
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        null=True,
                        verbose_name="Телефоны",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница с телефонными номерами",
                "verbose_name_plural": "Страницы с телефонными номерами",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AddField(
            model_name="helppage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "description",
                        wagtail.blocks.RichTextBlock(
                            features=[
                                "h2",
                                "h3",
                                "h4",
                                "h5",
                                "h6",
                                "bold",
                                "italic",
                                "link",
                                "code",
                                "blockquote",
                                "document-link",
                            ],
                            label="Текст",
                        ),
                    ),
                    (
                        "image_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Изображение", required=True
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        label="Подпись", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "embed_block",
                        wagtail.embeds.blocks.EmbedBlock(
                            help_text="Вставьте ссылку на контент, пример https://www.youtube.com/watch?v=SGJFWirQ3ks",
                            icon="media",
                            label="Встраиваемый контент",
                            template="blocks/embed_block.html",
                        ),
                    ),
                ],
                blank=True,
                null=True,
                verbose_name="Контент",
            ),
        ),
        migrations.AddField(
            model_name="helpsectionpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "description",
                        wagtail.blocks.RichTextBlock(
                            features=[
                                "h2",
                                "h3",
                                "h4",
                                "h5",
                                "h6",
                                "bold",
                                "italic",
                                "link",
                                "code",
                                "blockquote",
                                "document-link",
                            ],
                            label="Описание",
                        ),
                    )
                ],
                blank=True,
                null=True,
                verbose_name="О разделе",
            ),
        ),
        migrations.AddField(
            model_name="helpsectionpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Фоновое изображение раздела",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Изображение",
            ),
        ),
    ]
