# Generated by Django 5.0.2 on 2024-03-19 10:07

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("help", "0007_documentsamplepage_alter_phonespage_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phonespage",
            options={
                "verbose_name": "Страница с телефонами",
                "verbose_name_plural": "Страницы с телефонами",
            },
        ),
        migrations.RemoveField(
            model_name="documentsamplepage",
            name="phones",
        ),
        migrations.RemoveField(
            model_name="phonespage",
            name="documents",
        ),
        migrations.AddField(
            model_name="documentsamplepage",
            name="documents",
            field=wagtail.fields.StreamField(
                [
                    (
                        "documents_block",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "header",
                                    wagtail.blocks.CharBlock(
                                        label="Название документа", required=False
                                    ),
                                ),
                                (
                                    "document",
                                    wagtail.documents.blocks.DocumentChooserBlock(
                                        required=True
                                    ),
                                ),
                                (
                                    "document_example",
                                    wagtail.documents.blocks.DocumentChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "document_preview",
                                    wagtail.documents.blocks.DocumentChooserBlock(
                                        required=False
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                verbose_name="Документы",
            ),
        ),
        migrations.AddField(
            model_name="phonespage",
            name="phones",
            field=wagtail.fields.StreamField(
                [
                    (
                        "phones_block",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "header",
                                    wagtail.blocks.CharBlock(
                                        label="Название группы", required=False
                                    ),
                                ),
                                (
                                    "mobile_phone",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "phone",
                                                wagtail.blocks.RegexBlock(
                                                    error_messages={
                                                        "invalid": "Не верно введен номер"
                                                    },
                                                    help_text="Ввод без +7 в формате 9008887766",
                                                    label="Мобильный номер телефона",
                                                    max_length=10,
                                                    min_length=10,
                                                    regex="^[0-9]{10}$",
                                                    required=True,
                                                ),
                                            ),
                                            (
                                                "workplace",
                                                wagtail.blocks.CharBlock(
                                                    label="Рабочее место", required=True
                                                ),
                                            ),
                                            (
                                                "employee",
                                                wagtail.blocks.CharBlock(
                                                    label="Работник", required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "city_phone",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "phone",
                                                wagtail.blocks.RegexBlock(
                                                    error_messages={
                                                        "invalid": "Не верно введен номер"
                                                    },
                                                    help_text="Ввод без +74812 в формате 887766",
                                                    label="Городской номер телефона",
                                                    max_length=6,
                                                    min_length=6,
                                                    regex="^[0-9]{6}$",
                                                    required=True,
                                                ),
                                            ),
                                            (
                                                "workplace",
                                                wagtail.blocks.CharBlock(
                                                    label="Рабочее место", required=True
                                                ),
                                            ),
                                            (
                                                "employee",
                                                wagtail.blocks.CharBlock(
                                                    label="Работник", required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "internal_phone",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "phone",
                                                wagtail.blocks.RegexBlock(
                                                    error_messages={
                                                        "invalid": "Не верно введен номер"
                                                    },
                                                    help_text="Ввод в формате 123",
                                                    label="Внутренний номер телефона",
                                                    max_length=3,
                                                    min_length=3,
                                                    regex="^[0-9]{3}$",
                                                    required=True,
                                                ),
                                            ),
                                            (
                                                "workplace",
                                                wagtail.blocks.CharBlock(
                                                    label="Рабочее место", required=True
                                                ),
                                            ),
                                            (
                                                "employee",
                                                wagtail.blocks.CharBlock(
                                                    label="Работник", required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                verbose_name="Телефоны",
            ),
        ),
    ]
