# Generated by Django 5.0.2 on 2024-03-19 14:01

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("help", "0008_alter_phonespage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsamplepage",
            name="documents",
            field=wagtail.fields.StreamField(
                [
                    (
                        "documents_block",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "header",
                                    wagtail.blocks.CharBlock(
                                        label="Название документа", required=False
                                    ),
                                ),
                                (
                                    "document",
                                    wagtail.documents.blocks.DocumentChooserBlock(
                                        required=True
                                    ),
                                ),
                                (
                                    "document_example",
                                    wagtail.documents.blocks.DocumentChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "document_preview",
                                    wagtail.documents.blocks.DocumentChooserBlock(
                                        help_text="Выберите изображение или pdf для превью",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                verbose_name="Документы",
            ),
        ),
    ]
