# Generated by Django 5.0.2 on 2024-03-21 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("help", "0011_alter_helppage_body"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="helppage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Изображение",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Изображение",
            ),
        ),
    ]
