# Generated by Django 5.0.2 on 2024-03-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("help", "0012_helppage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="helpsectionpage",
            name="elements_per_page",
            field=models.IntegerField(
                default=12,
                help_text="Сколько элементов будет отображаться на странице",
                verbose_name="Количество элементов на странице",
            ),
        ),
    ]
