# Generated by Django 5.0.2 on 2024-03-03 08:28

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", wagtail.fields.RichTextField()),
            ],
            options={
                "verbose_name": "Футер",
                "verbose_name_plural": "Футеры",
            },
        ),
    ]
