# Generated by Django 5.0.2 on 2024-03-20 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Footer",
        ),
    ]
