# Generated by Django 5.0.2 on 2024-03-20 14:31

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base", "0002_delete_footer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название праздника",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "congratulatory_text",
                    wagtail.fields.RichTextField(
                        help_text="Введите текст поздравления",
                        verbose_name="Текст поздравления",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Выберите дату начала поздравления",
                        verbose_name="Дата начала поздравления",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Выберите дату окончания поздравления(если праздник однодневный необязательно)",
                        verbose_name="Дата окончания поздравления",
                    ),
                ),
            ],
            options={
                "verbose_name": "Праздник",
                "verbose_name_plural": "Праздники",
            },
        ),
    ]
