# Generated by Django 5.0.2 on 2024-03-03 10:51

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
        ("wagtailcore", "0091_remove_revision_submitted_for_moderation"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallerypage",
            name="body",
            field=wagtail.fields.StreamField(
                [("text", wagtail.blocks.RichTextBlock())], blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the image collection for this gallery.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wagtailcore.collection",
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Landscape mode only; horizontal width between 1000px and 3000px.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="introduction",
            field=models.TextField(blank=True, help_text="Text to describe the page"),
        ),
    ]
