# Generated by Django 5.0.2 on 2024-03-03 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_gallerypage_body_gallerypage_collection_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallerypage",
            name="introduction",
        ),
    ]
