# Generated by Django 5.0.2 on 2024-03-03 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0003_remove_gallerypage_introduction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gallerypage",
            old_name="image",
            new_name="g_image",
        ),
    ]
