# Generated by Django 5.0.2 on 2024-03-03 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0004_rename_image_gallerypage_g_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gallerypage",
            old_name="g_image",
            new_name="image",
        ),
    ]
