# Generated by Django 5.0.2 on 2024-03-18 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0005_rename_g_image_gallerypage_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallerypage",
            options={
                "verbose_name": "Страница галереи",
                "verbose_name_plural": "Страницы галереи",
            },
        ),
        migrations.AlterModelOptions(
            name="gallerysectionpage",
            options={
                "verbose_name": "Раздел галереи",
                "verbose_name_plural": "Разделы галереи",
            },
        ),
    ]
