# Generated by Django 5.0.2 on 2024-03-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0006_alter_gallerypage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallerysectionpage",
            name="menu_order_index",
            field=models.IntegerField(default=-1, verbose_name="Индекс сортировки"),
        ),
    ]
