# Generated by Django 5.0.2 on 2024-03-19 14:01

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0008_remove_gallerysectionpage_menu_order_index"),
        ("wagtailcore", "0091_remove_revision_submitted_for_moderation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallerypage",
            name="body",
        ),
        migrations.RemoveField(
            model_name="gallerypage",
            name="image",
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="images_per_page",
            field=models.IntegerField(
                default=8,
                help_text="How many images there should be on one page.",
                verbose_name="Images per page",
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Optional text to go with the intro text.",
                verbose_name="Intro text",
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="intro_title",
            field=models.CharField(
                blank=True,
                help_text="Optional H1 title for the gallery page.",
                max_length=250,
                verbose_name="Intro title",
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="order_images_by",
            field=models.IntegerField(
                choices=[(1, "Image title"), (2, "Newest image first")], default=1
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="use_lightbox",
            field=models.BooleanField(
                default=True,
                help_text="Use lightbox to view larger images when clicking the thumbnail.",
                verbose_name="Use lightbox",
            ),
        ),
        migrations.AlterField(
            model_name="gallerypage",
            name="collection",
            field=models.ForeignKey(
                help_text="Show images in this collection in the gallery view.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.collection",
                verbose_name="Collection",
            ),
        ),
    ]
