# Generated by Django 5.0.2 on 2024-03-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0009_remove_gallerypage_body_remove_gallerypage_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallerypage",
            name="images_per_page",
        ),
        migrations.RemoveField(
            model_name="gallerypage",
            name="order_images_by",
        ),
        migrations.RemoveField(
            model_name="gallerypage",
            name="use_lightbox",
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="elements_per_page",
            field=models.IntegerField(
                default=12,
                help_text="Сколько элементов будет отображаться на странице",
                verbose_name="Количество элементов на странице",
            ),
        ),
    ]
