# Generated by Django 5.0.2 on 2024-03-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0010_remove_gallerypage_images_per_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallerysectionpage",
            name="elements_per_page",
            field=models.IntegerField(
                default=12,
                help_text="Сколько элементов будет отображаться на странице",
                verbose_name="Количество элементов на странице",
            ),
        ),
    ]
