# Generated by Django 5.0.2 on 2024-03-21 13:17

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0011_gallerysectionpage_elements_per_page"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallerysectionpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "description",
                        wagtail.blocks.RichTextBlock(
                            features=[
                                "h2",
                                "h3",
                                "h4",
                                "h5",
                                "h6",
                                "bold",
                                "italic",
                                "link",
                                "code",
                                "blockquote",
                                "document-link",
                            ],
                            label="Описание",
                        ),
                    )
                ],
                blank=True,
                null=True,
                verbose_name="О разделе",
            ),
        ),
        migrations.AddField(
            model_name="gallerysectionpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Фоновое изображение раздела",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Изображение",
            ),
        ),
    ]
