# Generated by Django 5.0.2 on 2024-03-21 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0012_gallerysectionpage_body_gallerysectionpage_image"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallerypage",
            name="skin",
            field=models.ForeignKey(
                blank=True,
                help_text="Обложка",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Обложка (необязательно)",
            ),
        ),
    ]
