# Generated by Django 5.0.2 on 2024-03-27 06:56

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0013_gallerypage_skin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallerysectionpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "description",
                        wagtail.blocks.RichTextBlock(
                            features=[
                                "h2",
                                "h3",
                                "h4",
                                "h5",
                                "h6",
                                "bold",
                                "italic",
                                "link",
                                "code",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "document-link",
                            ],
                            label="Описание",
                        ),
                    )
                ],
                blank=True,
                null=True,
                verbose_name="О разделе",
            ),
        ),
    ]
