# Generated by Django 5.0.2 on 2024-03-18 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0002_technologysectionpage_menu_order_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technologysectionpage",
            name="menu_order_index",
        ),
    ]
