# Generated by Django 5.0.2 on 2024-03-19 05:33

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0003_remove_technologysectionpage_menu_order_index"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="technologysectionpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "description",
                        wagtail.blocks.RichTextBlock(
                            features=[
                                "h2",
                                "h3",
                                "h4",
                                "h5",
                                "h6bold",
                                "italic",
                                "link",
                                "document-link",
                                "code",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "blockquote",
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="technologysectionpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Фото раздела",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
