# Generated by Django 5.0.2 on 2024-03-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0009_technologypage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="technologysectionpage",
            name="elements_per_page",
            field=models.IntegerField(
                default=12,
                help_text="Сколько элементов будет отображаться на странице",
                verbose_name="Количество элементов на странице",
            ),
        ),
    ]
