# Generated by Django 5.0.2 on 2024-03-03 15:51

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspage",
            name="body",
            field=wagtail.fields.StreamField(
                [("text", wagtail.blocks.RichTextBlock())], blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="newspage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="News image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
