# Generated by Django 5.0.2 on 2024-03-18 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_newspage_body_newspage_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newspage",
            options={
                "verbose_name": "Страница новости",
                "verbose_name_plural": "Страницы новостей",
            },
        ),
        migrations.AlterModelOptions(
            name="newssectionpage",
            options={
                "verbose_name": "Раздела новостей",
                "verbose_name_plural": "Разделы новостей",
            },
        ),
    ]
