# Generated by Django 5.0.2 on 2024-03-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_alter_newspage_options_alter_newssectionpage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="newssectionpage",
            name="menu_order_index",
            field=models.IntegerField(default=-1, verbose_name="Индекс сортировки"),
        ),
    ]
