# Generated by Django 5.0.2 on 2024-03-20 07:33

import django.db.models.deletion
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtailmedia.blocks
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_remove_newssectionpage_menu_order_index"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newspage",
            name="image",
        ),
        migrations.AddField(
            model_name="newssectionpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "description",
                        wagtail.blocks.RichTextBlock(
                            features=[
                                "h2",
                                "h3",
                                "h4",
                                "h5",
                                "h6",
                                "bold",
                                "italic",
                                "link",
                                "code",
                                "blockquote",
                                "document-link",
                            ],
                            label="Описание",
                        ),
                    )
                ],
                blank=True,
                null=True,
                verbose_name="О разделе",
            ),
        ),
        migrations.AddField(
            model_name="newssectionpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Фоновое изображение раздела",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="newspage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "description",
                        wagtail.blocks.RichTextBlock(
                            features=[
                                "h2",
                                "h3",
                                "h4",
                                "h5",
                                "h6",
                                "bold",
                                "italic",
                                "link",
                                "code",
                                "blockquote",
                                "document-link",
                            ],
                            label="Текст",
                        ),
                    ),
                    (
                        "image_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Изображение", required=True
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        label="Подпись", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "embed_block",
                        wagtail.embeds.blocks.EmbedBlock(
                            help_text="Вставьте ссылку на контент, пример https://www.youtube.com/watch?v=SGJFWirQ3ks",
                            icon="media",
                            label="Встраиваемый контент",
                            template="blocks/embed_block.html",
                        ),
                    ),
                    ("audio", wagtailmedia.blocks.AudioChooserBlock(label="Аудио")),
                    ("video", wagtailmedia.blocks.VideoChooserBlock(label="Видео")),
                ],
                blank=True,
                null=True,
                verbose_name="Контент",
            ),
        ),
    ]
