# Generated by Django 5.0.2 on 2024-03-04 16:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authjournal",
            name="event_type",
        ),
    ]
