# Generated by Django 5.0.2 on 2024-03-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service_app", "0002_remove_authjournal_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="authjournal",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("Авторизация", "Login"),
                    ("Выход", "Logout"),
                    ("Авторизация с ошибкой", "Login Failed"),
                ],
                default="Авторизация с ошибкой",
                max_length=50,
            ),
        ),
    ]
